# Generated by Django 4.2.5 on 2023-11-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_remove_reservation_pickup_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='img',
            field=models.ImageField(default='img', upload_to='img'),
            preserve_default=False,
        ),
    ]
